### PR TITLE
Update firmware install status for scheduling state

### PR DESCRIPTION
**Pull request by coffeefreak101**
## What does this PR implement/change/remove?

During my firmware update testing, I encountered a situation where the firmware update status went from "initializing" to "running" for just a second, then to "powercycle-host" then back to "running".

This occurred because the BMC's "scheduling" state gets reported as "running", and the "scheduled" state is reported as "powercycle-host".

This change moves "scheduling" BMC state to the "initializing" firmware update status.

### CODE REVIEW

**Comment by joelrebel** [comment]
good catch,
Since theres an ongoing overhaul in these changes - do you mind basing this PR off this branch https://github.com/bmc-toolbox/bmclib/tree/redfish-dell

**Comment by coffeefreak101** [comment]
> good catch, Since theres an ongoing overhaul in this area - do you mind basing this PR off this branch https://github.com/bmc-toolbox/bmclib/tree/redfish-dell

I see you're moving the firmware file in that branch. Looks like your PR has the approvals. I can wait for that to merge first before merging this one.

**Comment by coffeefreak101** [comment]
@joelrebel 

I rebased and fixed this base on the new code.

**Review by joelrebel — APPROVED** [review]
Thanks for fixing this up

**Pull request merged**
