### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by omar-m-othman**
I also ran `gofmt -w .`.

### CODE REVIEW

**Comment by omar-m-othman** [comment]
@jacobweinstock: There is something wrong with the runner. I am running the exact same command (CGO_ENABLED=0 go test -gcflags=-l -v -covermode=count ./...) on my VM and the tests are passing. The error I am getting [here](https://github.com/bmc-toolbox/bmclib/pull/200/checks?check_run_id=1910523872) is super weird, I don't even have that dependency (golang.org/x/tools@v0.1.0) in go.mod!

**Comment by joelrebel** [comment]
Hey @omar-m-othman is there any reason bmclib should include the `vendor` directory with dependencies,
As long as the `go.mod` `go.sum` files are updated - its not necessary to have dependencies vendored in.

**Comment by omar-m-othman** [comment]
> Hey @omar-m-othman is there any reason bmclib should include the `vendor` directory with dependencies,
> As long as the `go.mod` `go.sum` files are updated - its not necessary to have dependencies vendored in.

Hey @joelrebel,

Cool, done! Thanks for the advice, modules is always a complex topic for me... :-)

**Review by joelrebel — APPROVED** [review]
to cover formatting/linting, added a issue here -  https://github.com/bmc-toolbox/bmclib/issues/204

**Pull request merged**
